
import { Asset } from './types';

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'ASSET-001',
    serialNumber: 'BLD-KH-001',
    name: 'Main Admin Building',
    model: 'Type-A Modular',
    category: 'Buildings',
    purchaseDate: '2015-06-15',
    installationDate: '2015-08-01',
    purchaseValue: 5000000,
    currentBookValue: 3850000,
    location: 'Khodad',
    department: 'Administration',
    status: 'Active',
    depreciationRate: 5,
    vendorName: 'Global Construction Corp'
  },
  {
    id: 'ASSET-002',
    brand: 'Ford',
    serialNumber: 'VEH-MN-022',
    name: 'Logistics Van 4',
    model: 'Transit V363',
    category: 'Vehicles',
    purchaseDate: '2022-11-20',
    installationDate: '2022-11-21',
    purchaseValue: 25000,
    currentBookValue: 18500,
    location: 'Manjarwadi',
    department: 'Logistics',
    status: 'Active',
    depreciationRate: 15,
    warrantyPeriodMonths: 36,
    warrantyExpiry: '2025-11-20',
    vendorName: 'Swift Motors'
  },
  {
    id: 'ASSET-003',
    brand: 'Dell',
    serialNumber: 'IT-SL-505',
    name: 'High Performance Server R740',
    model: 'PowerEdge R740',
    category: 'IT Equipment',
    purchaseDate: '2023-01-10',
    installationDate: '2023-01-15',
    purchaseValue: 12000,
    currentBookValue: 8000,
    location: 'Sultanpur',
    department: 'IT',
    status: 'Active',
    depreciationRate: 33.33,
    warrantyPeriodMonths: 36,
    warrantyExpiry: '2026-01-10',
    vendorName: 'Dell Enterprise'
  },
  {
    id: 'ASSET-004',
    brand: 'Haas',
    serialNumber: 'MAC-GH-101',
    name: 'CNC Milling Machine',
    model: 'VF-2SS',
    category: 'Electronics Machinery',
    purchaseDate: '2020-03-05',
    installationDate: '2020-04-10',
    purchaseValue: 150000,
    currentBookValue: 95000,
    location: 'Ghodegaon',
    department: 'Manufacturing',
    status: 'Under Repair',
    depreciationRate: 15,
    vendorName: 'Precision Tools Ltd'
  },
  {
    id: 'ASSET-005',
    serialNumber: 'LND-KH-99',
    name: 'East Expansion Plot',
    category: 'Building Lands',
    purchaseDate: '2010-01-01',
    installationDate: '2010-01-01',
    purchaseValue: 1200000,
    currentBookValue: 1200000,
    location: 'Khodad',
    department: 'Real Estate',
    status: 'Active',
    depreciationRate: 0,
    vendorName: 'Local Authority'
  }
];
